/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
  BaseContract,
  ContractTransaction,
  Overrides,
  CallOverrides,
} from "ethers";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";
import { TypedEventFilter, TypedEvent, TypedListener } from "./commons";

interface BondingCurveInterface extends ethers.utils.Interface {
  functions: {
    "calculateInitializationReturn(uint256,uint32)": FunctionFragment;
    "calculatePurchaseReturn(uint256,uint256,uint32,uint256)": FunctionFragment;
    "calculateSaleReturn(uint256,uint256,uint32,uint256)": FunctionFragment;
    "initMaxExpArray()": FunctionFragment;
    "maxRatio()": FunctionFragment;
    "slopeFactor()": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "calculateInitializationReturn",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "calculatePurchaseReturn",
    values: [BigNumberish, BigNumberish, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "calculateSaleReturn",
    values: [BigNumberish, BigNumberish, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "initMaxExpArray",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "maxRatio", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "slopeFactor",
    values?: undefined
  ): string;

  decodeFunctionResult(
    functionFragment: "calculateInitializationReturn",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "calculatePurchaseReturn",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "calculateSaleReturn",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "initMaxExpArray",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "maxRatio", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "slopeFactor",
    data: BytesLike
  ): Result;

  events: {};
}

export class BondingCurve extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  listeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter?: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): Array<TypedListener<EventArgsArray, EventArgsObject>>;
  off<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  on<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  once<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeListener<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeAllListeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): this;

  listeners(eventName?: string): Array<Listener>;
  off(eventName: string, listener: Listener): this;
  on(eventName: string, listener: Listener): this;
  once(eventName: string, listener: Listener): this;
  removeListener(eventName: string, listener: Listener): this;
  removeAllListeners(eventName?: string): this;

  queryFilter<EventArgsArray extends Array<any>, EventArgsObject>(
    event: TypedEventFilter<EventArgsArray, EventArgsObject>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEvent<EventArgsArray & EventArgsObject>>>;

  interface: BondingCurveInterface;

  functions: {
    calculateInitializationReturn(
      _price: BigNumberish,
      _reserveRatio: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    calculatePurchaseReturn(
      _supply: BigNumberish,
      _poolBalance: BigNumberish,
      _reserveRatio: BigNumberish,
      _price: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    calculateSaleReturn(
      _supply: BigNumberish,
      _poolBalance: BigNumberish,
      _reserveRatio: BigNumberish,
      _tokens: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    initMaxExpArray(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    maxRatio(overrides?: CallOverrides): Promise<[number]>;

    slopeFactor(overrides?: CallOverrides): Promise<[BigNumber]>;
  };

  calculateInitializationReturn(
    _price: BigNumberish,
    _reserveRatio: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  calculatePurchaseReturn(
    _supply: BigNumberish,
    _poolBalance: BigNumberish,
    _reserveRatio: BigNumberish,
    _price: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  calculateSaleReturn(
    _supply: BigNumberish,
    _poolBalance: BigNumberish,
    _reserveRatio: BigNumberish,
    _tokens: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  initMaxExpArray(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  maxRatio(overrides?: CallOverrides): Promise<number>;

  slopeFactor(overrides?: CallOverrides): Promise<BigNumber>;

  callStatic: {
    calculateInitializationReturn(
      _price: BigNumberish,
      _reserveRatio: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    calculatePurchaseReturn(
      _supply: BigNumberish,
      _poolBalance: BigNumberish,
      _reserveRatio: BigNumberish,
      _price: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    calculateSaleReturn(
      _supply: BigNumberish,
      _poolBalance: BigNumberish,
      _reserveRatio: BigNumberish,
      _tokens: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    initMaxExpArray(overrides?: CallOverrides): Promise<void>;

    maxRatio(overrides?: CallOverrides): Promise<number>;

    slopeFactor(overrides?: CallOverrides): Promise<BigNumber>;
  };

  filters: {};

  estimateGas: {
    calculateInitializationReturn(
      _price: BigNumberish,
      _reserveRatio: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    calculatePurchaseReturn(
      _supply: BigNumberish,
      _poolBalance: BigNumberish,
      _reserveRatio: BigNumberish,
      _price: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    calculateSaleReturn(
      _supply: BigNumberish,
      _poolBalance: BigNumberish,
      _reserveRatio: BigNumberish,
      _tokens: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    initMaxExpArray(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    maxRatio(overrides?: CallOverrides): Promise<BigNumber>;

    slopeFactor(overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    calculateInitializationReturn(
      _price: BigNumberish,
      _reserveRatio: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    calculatePurchaseReturn(
      _supply: BigNumberish,
      _poolBalance: BigNumberish,
      _reserveRatio: BigNumberish,
      _price: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    calculateSaleReturn(
      _supply: BigNumberish,
      _poolBalance: BigNumberish,
      _reserveRatio: BigNumberish,
      _tokens: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    initMaxExpArray(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    maxRatio(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    slopeFactor(overrides?: CallOverrides): Promise<PopulatedTransaction>;
  };
}
