/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
  BaseContract,
  ContractTransaction,
  Overrides,
  CallOverrides,
} from "ethers";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";
import { TypedEventFilter, TypedEvent, TypedListener } from "./commons";

interface CryptomediaFactoryInterface extends ethers.utils.Interface {
  functions: {
    "DEPLOY_WITH_SIG_TYPEHASH()": FunctionFragment;
    "bondingCurve()": FunctionFragment;
    "createCryptomediaWithSig(address,tuple,uint256,tuple)": FunctionFragment;
    "deployWithSigNonces(address)": FunctionFragment;
    "logic()": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "DEPLOY_WITH_SIG_TYPEHASH",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "bondingCurve",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "createCryptomediaWithSig",
    values: [
      string,
      {
        tokenURI: string;
        metadataURI: string;
        contentHash: BytesLike;
        metadataHash: BytesLike;
      },
      BigNumberish,
      { deadline: BigNumberish; v: BigNumberish; r: BytesLike; s: BytesLike }
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "deployWithSigNonces",
    values: [string]
  ): string;
  encodeFunctionData(functionFragment: "logic", values?: undefined): string;

  decodeFunctionResult(
    functionFragment: "DEPLOY_WITH_SIG_TYPEHASH",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "bondingCurve",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "createCryptomediaWithSig",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "deployWithSigNonces",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "logic", data: BytesLike): Result;

  events: {
    "CryptomediaDeployed(address,address,uint256)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "CryptomediaDeployed"): EventFragment;
}

export type CryptomediaDeployedEvent = TypedEvent<
  [string, string, BigNumber] & {
    contractAddress: string;
    creator: string;
    feePct: BigNumber;
  }
>;

export class CryptomediaFactory extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  listeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter?: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): Array<TypedListener<EventArgsArray, EventArgsObject>>;
  off<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  on<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  once<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeListener<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeAllListeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): this;

  listeners(eventName?: string): Array<Listener>;
  off(eventName: string, listener: Listener): this;
  on(eventName: string, listener: Listener): this;
  once(eventName: string, listener: Listener): this;
  removeListener(eventName: string, listener: Listener): this;
  removeAllListeners(eventName?: string): this;

  queryFilter<EventArgsArray extends Array<any>, EventArgsObject>(
    event: TypedEventFilter<EventArgsArray, EventArgsObject>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEvent<EventArgsArray & EventArgsObject>>>;

  interface: CryptomediaFactoryInterface;

  functions: {
    DEPLOY_WITH_SIG_TYPEHASH(overrides?: CallOverrides): Promise<[string]>;

    bondingCurve(overrides?: CallOverrides): Promise<[string]>;

    createCryptomediaWithSig(
      creator: string,
      data: {
        tokenURI: string;
        metadataURI: string;
        contentHash: BytesLike;
        metadataHash: BytesLike;
      },
      feePct: BigNumberish,
      sig: {
        deadline: BigNumberish;
        v: BigNumberish;
        r: BytesLike;
        s: BytesLike;
      },
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    deployWithSigNonces(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    logic(overrides?: CallOverrides): Promise<[string]>;
  };

  DEPLOY_WITH_SIG_TYPEHASH(overrides?: CallOverrides): Promise<string>;

  bondingCurve(overrides?: CallOverrides): Promise<string>;

  createCryptomediaWithSig(
    creator: string,
    data: {
      tokenURI: string;
      metadataURI: string;
      contentHash: BytesLike;
      metadataHash: BytesLike;
    },
    feePct: BigNumberish,
    sig: {
      deadline: BigNumberish;
      v: BigNumberish;
      r: BytesLike;
      s: BytesLike;
    },
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  deployWithSigNonces(
    arg0: string,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  logic(overrides?: CallOverrides): Promise<string>;

  callStatic: {
    DEPLOY_WITH_SIG_TYPEHASH(overrides?: CallOverrides): Promise<string>;

    bondingCurve(overrides?: CallOverrides): Promise<string>;

    createCryptomediaWithSig(
      creator: string,
      data: {
        tokenURI: string;
        metadataURI: string;
        contentHash: BytesLike;
        metadataHash: BytesLike;
      },
      feePct: BigNumberish,
      sig: {
        deadline: BigNumberish;
        v: BigNumberish;
        r: BytesLike;
        s: BytesLike;
      },
      overrides?: CallOverrides
    ): Promise<string>;

    deployWithSigNonces(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    logic(overrides?: CallOverrides): Promise<string>;
  };

  filters: {
    "CryptomediaDeployed(address,address,uint256)"(
      contractAddress?: string | null,
      creator?: string | null,
      feePct?: null
    ): TypedEventFilter<
      [string, string, BigNumber],
      { contractAddress: string; creator: string; feePct: BigNumber }
    >;

    CryptomediaDeployed(
      contractAddress?: string | null,
      creator?: string | null,
      feePct?: null
    ): TypedEventFilter<
      [string, string, BigNumber],
      { contractAddress: string; creator: string; feePct: BigNumber }
    >;
  };

  estimateGas: {
    DEPLOY_WITH_SIG_TYPEHASH(overrides?: CallOverrides): Promise<BigNumber>;

    bondingCurve(overrides?: CallOverrides): Promise<BigNumber>;

    createCryptomediaWithSig(
      creator: string,
      data: {
        tokenURI: string;
        metadataURI: string;
        contentHash: BytesLike;
        metadataHash: BytesLike;
      },
      feePct: BigNumberish,
      sig: {
        deadline: BigNumberish;
        v: BigNumberish;
        r: BytesLike;
        s: BytesLike;
      },
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    deployWithSigNonces(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    logic(overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    DEPLOY_WITH_SIG_TYPEHASH(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    bondingCurve(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    createCryptomediaWithSig(
      creator: string,
      data: {
        tokenURI: string;
        metadataURI: string;
        contentHash: BytesLike;
        metadataHash: BytesLike;
      },
      feePct: BigNumberish,
      sig: {
        deadline: BigNumberish;
        v: BigNumberish;
        r: BytesLike;
        s: BytesLike;
      },
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    deployWithSigNonces(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    logic(overrides?: CallOverrides): Promise<PopulatedTransaction>;
  };
}
