/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type { IBondingCurve, IBondingCurveInterface } from "../IBondingCurve";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint32",
        name: "_reserveRatio",
        type: "uint32",
      },
    ],
    name: "calculateInitializationPrice",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "pure",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "_price",
        type: "uint256",
      },
      {
        internalType: "uint32",
        name: "_reserveRatio",
        type: "uint32",
      },
    ],
    name: "calculateInitializationReturn",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "_supply",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "_poolBalance",
        type: "uint256",
      },
      {
        internalType: "uint32",
        name: "_reserveRatio",
        type: "uint32",
      },
      {
        internalType: "uint256",
        name: "_tokens",
        type: "uint256",
      },
    ],
    name: "calculatePrice",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "_supply",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "_poolBalance",
        type: "uint256",
      },
      {
        internalType: "uint32",
        name: "_reserveRatio",
        type: "uint32",
      },
      {
        internalType: "uint256",
        name: "_price",
        type: "uint256",
      },
    ],
    name: "calculatePurchaseReturn",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "_supply",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "_poolBalance",
        type: "uint256",
      },
      {
        internalType: "uint32",
        name: "_reserveRatio",
        type: "uint32",
      },
      {
        internalType: "uint256",
        name: "_tokens",
        type: "uint256",
      },
    ],
    name: "calculateSaleReturn",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
];

export class IBondingCurve__factory {
  static readonly abi = _abi;
  static createInterface(): IBondingCurveInterface {
    return new utils.Interface(_abi) as IBondingCurveInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IBondingCurve {
    return new Contract(address, _abi, signerOrProvider) as IBondingCurve;
  }
}
