/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type { ICryptomedia, ICryptomediaInterface } from "../ICryptomedia";

const _abi = [
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "uint256",
        name: "_tokenId",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "address",
        name: "owner",
        type: "address",
      },
      {
        indexed: false,
        internalType: "string",
        name: "_uri",
        type: "string",
      },
    ],
    name: "TokenMetadataURIUpdated",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "uint256",
        name: "_tokenId",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "address",
        name: "owner",
        type: "address",
      },
      {
        indexed: false,
        internalType: "string",
        name: "_uri",
        type: "string",
      },
    ],
    name: "TokenURIUpdated",
    type: "event",
  },
];

export class ICryptomedia__factory {
  static readonly abi = _abi;
  static createInterface(): ICryptomediaInterface {
    return new utils.Interface(_abi) as ICryptomediaInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): ICryptomedia {
    return new Contract(address, _abi, signerOrProvider) as ICryptomedia;
  }
}
